# -*-coding:utf-8-unix;mode:yaml-*-

#  Copyright 2024 hanepjiv
#  @author hanepjiv <hanepjiv@gmail.com>
#  @copyright The MIT License (MIT) / Apache License Version 2.0
#  @since 2024/11/09
#  @date 2025/09/21

name: CI Rust

on:
  workflow_call:
    inputs:
      apt-packages:
        description: |
          comma separated apt-packages. \'apt-get install -y -qq <package>\'
        required: false
        type: string
    secrets:
      ssh-private-keys:
        required: false

env:
  CARGO_TERM_COLOR: always

jobs:
  params:
    runs-on: ubuntu-latest

    outputs:
      cache-rust-toolchain-path: |
        ~/.cargo/
        ~/.rustup/

      cache-rust-target-path: |
        ~/.cargo/.crates.toml
        ~/.cargo/.crates2.json
        ~/.cargo/bin/
        ~/.cargo/registry/index/
        ~/.cargo/registry/cache/
        ~/.cargo/git/db/
        target/

      repos: ${{ steps.repos.outputs.ret }}
      date: ${{ steps.date.outputs.ret }}

      cache-rust-toolchain-key: ${{ runner.os }}-${{ runner.arch }}-rust-toolchain-${{ steps.date.outputs.ret }}
      cache-rust-target-key: ${{ runner.os }}-${{ runner.arch }}-${{ steps.repos.outputs.ret }}-rust-target

      pkgs: ${{ steps.pkgs.outputs.ret00 }}
      pkgs_sha: ${{ steps.pkgs.outputs.ret01 }}

    steps:
      - id: repos
        run: echo "ret=${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}" >> $GITHUB_OUTPUT

      - id: date
        env:
          TZ: "TZ"
        run: echo "ret=$(date +'%Y%0m%0d')" >> $GITHUB_OUTPUT

      - id: pkgs
        run: |
          PKGS="${{ inputs.apt-packages }}"
          PKGS="${PKGS//,/ }"
          echo "ret00=$PKGS" >> $GITHUB_OUTPUT
          echo "ret01=`echo $PKGS | sha256sum | cut -f1 -d' '`" >> $GITHUB_OUTPUT

  cargo:
    runs-on: ubuntu-latest

    needs: params

    permissions:
      contents: read
      issues: write

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          cat <<EOF > ~/.ssh/config
          Host github.com
            User git
            Hostname github.com
          EOF
          chmod 600 ~/.ssh/config

          if [[ '' != "${{ secrets.ssh-private-keys }}" ]]; then
            IFS=, inputs=("${{ secrets.ssh-private-keys }}")
            for i in ${inputs[@]}
            do key=`echo $i | grep -v '^$'` # trim blank line
               out=~/.ssh/`echo $key | sha256sum | cut -f1 -d' '`
               echo $key > $out
               chmod 600 $out
               echo "  IdentityFile $out" >> ~/.ssh/config
            done
          fi

          eval `ssh-agent -s`

      - name: Setup git
        run: |
          cat <<EOF > ~/.gitconfig
          [credential]
          helper = cache
          EOF

      - name: Update apt
        run: |
          sudo apt-get update -y -qq

      - name: Install apt-packages
        if: inputs.apt-packages != ''
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: ${{ needs.params.outputs.pkgs }}
          version: ${{ needs.params.outputs.pkgs_sha }}

      - name: Restore cached Rust toolchain
        id: cache-rust-toolchain-restore
        uses: actions/cache/restore@v4
        with:
          path: ${{ needs.params.outputs.cache-rust-toolchain-path }}
          key: ${{ needs.params.outputs.cache-rust-toolchain-key }}

      - name: Setup Rust Toolchain
        if: steps.cache-rust-toolchain-restore.outputs.cache-hit != 'true'
        run: |
          if ! [[ -x "$(command -v rustup)" ]]; then
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | \
            sh -s -- -y
          fi

          source ~/.cargo/env

          cat <<EOF >> ~/.cargo/config.toml
          [net]
          git-fetch-with-cli = true
          EOF

          rustup set profile minimal
          rustup install stable beta nightly
          rustup component add --toolchain stable clippy
          rustup component add --toolchain beta clippy
          rustup component add --toolchain nightly clippy

          curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash

          cargo binstall -y cargo-deny cargo-msrv

      - name: Save cached Rust toolchain
        if: steps.cache-rust-toolchain-restore.outputs.cache-hit != 'true'
        id: cache-rust-toolchain-save
        uses: actions/cache/save@v4
        with:
          path: ${{ needs.params.outputs.cache-rust-toolchain-path }}
          key: ${{ needs.params.outputs.cache-rust-toolchain-key }}

      - uses: actions/checkout@v5

      - name: Run cargo update
        run: |
          source ~/.cargo/env
          cargo update

      - name: Restore cached Rust target
        id: cache-rust-target-restore
        uses: actions/cache/restore@v4
        with:
          path: ${{ needs.params.outputs.cache-rust-target-path }}
          key: ${{ needs.params.outputs.cache-rust-target-key }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Run rust_allchecks
        run: |
          source ~/.cargo/env
          git clone https://gist.github.com/dbf8aecb6a66ed2119a1107c35c54b32.git ${GITHUB_WORKSPACE}/../rust_allchecks
          ${GITHUB_WORKSPACE}/../rust_allchecks/rust_allchecks.sh

      - name: Save cached Rust target
        if: steps.cache-rust-target-restore.outputs.cache-hit != 'true'
        id: cache-rust-target-save
        uses: actions/cache/save@v4
        with:
          path: ${{ needs.params.outputs.cache-rust-target-path }}
          key: ${{ needs.params.outputs.cache-rust-target-key }}-${{ hashFiles('**/Cargo.lock') }} # use new hash

      - name: Create issue when failed
        if: ${{ failure() }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}

          TITLE: CI Rust failed
          ASSIGNEES: ${{ github.actor }}
          LABELS: workflows,ci
          BODY: |
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

            https://github.com/${{ github.repository }}/tree/${{ github.ref_name }}

          PINNED: true
          CLOSE_PREVIOUS: true
        run: |
          if [[ $CLOSE_PREVIOUS == true ]]; then
            previous_issue_number=$(gh issue list \
              --label "$LABELS" \
              --json number \
              --jq '.[0].number')
            if [[ -n $previous_issue_number ]]; then
              gh issue close "$previous_issue_number"
              gh issue unpin "$previous_issue_number"
            fi
          fi
          new_issue_url=$(gh issue create \
            --title "$TITLE" \
            --assignee "$ASSIGNEES" \
            --label "$LABELS" \
            --body "$BODY")
          if [[ $PINNED == true ]]; then
            gh issue pin "$new_issue_url"
          fi
