# -*-coding:utf-8-unix;mode:yml-*-

#  Copyright 2024 hanepjiv
#  @author hanepjiv <hanepjiv@gmail.com>
#  @copyright The MIT License (MIT) / Apache License Version 2.0
#  @since 2024/11/09
#  @date 2024/11/11

name: Call a reusable workflow

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

jobs:
  ci-rust:
    permissions:
      contents: read
      issues: write
    uses: ./.github/workflows/ci-rust.yml # reuse local repository
