name: Call a reusable workflow

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

jobs:
  ci-rust:
    permissions:
      contents: read
      issues: write
    uses: ./.github/workflows/ci-rust.yml # reuse local repository
